local MOD_STRINGS =
{
	OPTIONS =
	{
		OF_RESCUABLE = "DOC RESCUABLE",
		OF_RESCUABLE_DESC = "Whether On-File Doc can be rescued from a Detention Center",
	},
	AGENTS =
	{
		DOC =
		{
			NAME = "Doc",
			FILE = "MOMO-001",
			FULLNAME = "PLACEHOLDERNAME",
			HOMETOWN = "PLACEHOLDERHOMETOWN",
			RESCUED = "PLACEHOLDERRESCUED",
			BANTER = {
				START ={
					"PLACEHOLDERBANTERSTART1",
					"PLACEHOLDERBANTERSTART2",
				},
				FINAL_WORDS =
				{
					"PLACEHOLDERBANTERFINALWORDS1",
					"PLACEHOLDERBANTERFINALWORDS2",
				},
			},
			ALT_1 =
			{
				TOOLTIP = "PLACEHOLDERTOOLTIP",
				BIO = "PLACEHOLDERBIO",
				YEARS_OF_SERVICE = "PLACEHOLDERYOS",
				AGE = "PLACEHOLDERAGE",
			},
		},
	},
	ITEMS =
	{
		AUGMENT_MONITOR = "Monitor",
		AUGMENT_MONITOR_DESC = "PLACEHOLDERDESC1",
		AUGMENT_MONITOR_FLAV = "PLACEHOLDERFLAV1",
		ITEM_DRUG_PISTOL = "Syringe Pistol",
		ITEM_DRUG_PISTOL_DESC = "PLACEHOLDERDESC2",
		ITEM_DRUG_PISTOL_FLAV = "PLACEHOLDERFLAV2",
	},
	ABILITIES =
	{
		ABILITY_MONITOR = "Monitor",
		ABILITY_ACTIVATE_INJECTED_DOSE_NAME = "Activate Injected Dose",
		ABILITY_ACTIVATE_INJECTED_DOSE_ACTIVATE = "Activate ",
		ABILITY_SHOOT_STIM = "Shoot Stim",
		ABILITY_SHOOT_STIM_DESC = "Shoot Stim desc",
		ABILITY_NO_STIM = "No stim",
		ABILITY_SHOOT_MEDGEL = "Shoot Med Gel",
		ABILITY_SHOOT_MEDGEL_DESC = "Shoot Med Gel desc",
		ABILITY_NO_MEDGEL = "No Med Gel",
		ABILITY_SHOOT_DEFIBLANCE = "Shoot Ventricular Lance",
		ABILITY_SHOOT_DEFIBLANCE_DESC = "Shoot Ventricular Lance desc",
		ABILITY_NO_DEFIBLANCE = "No Ventricular Lance",
	},
}
return MOD_STRINGS